front:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mysql:mysql
    # - mongo:mongo
    - memcached:memcached
    # - redis:redis
    # - elasticsearch:elasticsearch
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor
    - ./conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./conf/php.ini:/etc/php5/fpm/conf.d/40-custom.ini
    - ./conf/php-cli.ini:/etc/php5/cli/conf.d/40-custom.ini

mysql:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
   - /var/lib/mysql
  environment:
    MYSQL_DATABASE: drupal
    MYSQL_ROOT_PASSWORD: root

#mongo:
#  image: mongo
#  ports:
#    - "27017:27017"

memcached:
  image: memcached
  ports:
    - "11211:11211"

#redis:
#  image: redis
#  ports:
#    - "6379:6379"

# elasticsearch:
#  image: elasticsearch
#  ports:
#    - "9200:9200"
#    - "9300:9300"
